name: nu_challenge
description: "Nubank Mobile Take-Home Test"


publish_to: 'none' 

version: 1.0.1+2

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  flutter_bloc: ^9.1.1
  go_router: ^16.0.0
  google_fonts: ^6.2.1
  flutter_svg: ^2.2.0
  bloc: ^9.0.0
  meta: ^1.16.0
  package_info_plus: ^8.3.0
  url_launcher: ^6.3.1
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  bloc_test: ^10.0.0
  mocktail: ^1.0.4
  test_coverage_badge: ^0.3.2
  mockito: ^5.4.6
  integration_test:
    sdk: flutter


flutter:  
  uses-material-design: true
  assets:
    - google_fonts/
    - assets/svgs/

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
